title: Hi, I'm Sneha Jaikumar!
description: I am a Data Scientist
baseurl: ""
url: https://snehajaikumar23.github.io

# site settings
taglong: Jekyll theme for a beautiful online CV
tagshort: Jekyll theme

# author settings
author:
  name: Sneha Jaikumar
  email: sj3474@columbia.edu
photo: assets/files/photo.jpg
joblines:
  - Columbia University
  - Master's Student, Data Science

# profile links
profile:
  linkedin: https://www.linkedin.com/in/snehajaikumar
  github: https://github.com/snehajaikumar23
  cv: false

# build settings
permalink: pretty
exclude:
  - LICENSE
  - README.md
  - Gemfile
  - vendor/

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  sourcemap: never
  
