title: Hi, I'm Sneha!
description: ""
baseurl: ""
url: https://snehajaikumar23.github.io

# site settings
taglong: I’m a researcher and data scientist focused on building intelligent systems that can learn from complex data and respond meaningfully in the real world. I’m particularly strong at bridging machine learning research with practical software, designing pipelines that move beyond theory and scale to real use. Based out of NYC
tagshort: Jekyll theme

# author settings
author:
  name: Sneha Jaikumar
  email: sj3474@columbia.edu
photo: assets/files/photo.jpg
joblines:
  - Columbia University
  - Master's Student, Data Science

# profile links
profile:
  linkedin: https://www.linkedin.com/in/sneha-jaikumar
  github: https://github.com/snehajaikumar23
  cv: false

# build settings
permalink: pretty
exclude:
  - LICENSE
  - README.md
  - Gemfile
  - vendor/

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  sourcemap: never
  
