title: Sneha Jaikumar
hero_title: Hi, I’m Sneha!
description: "Researcher and data scientist focused on building intelligent systems that can learn from complex data and respond meaningfully in the real world."
baseurl: ""
url: https://snehajaikumar23.github.io

# site settings
taglong: I’m a data scientist and researcher currently pursuing my M.S. in Data Science at Columbia University. I enjoy turning messy, complex data into systems that work in the real world, from research pipelines to production-ready software. Based in NYC.
tagshort: ""

# author settings
author:
  name: Sneha Jaikumar
  email: sj3474@columbia.edu
photo: assets/files/photo.jpg
joblines:
  - Columbia University
  - Master's Student, Data Science

# profile links
profile:
  linkedin: https://www.linkedin.com/in/sneha-jaikumar
  github: https://github.com/snehajaikumar23
  cv: false

# build settings
permalink: pretty
exclude:
  - LICENSE
  - README.md
  - Gemfile
  - vendor/

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  sourcemap: never
  
